# Generated by Django 5.0.4 on 2024-05-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courses',
            new_name='course_name',
        ),
    ]
