# Generated by Django 5.0.4 on 2024-05-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_courses_student_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_name',
            new_name='courses',
        ),
    ]
